name: Build PHP Extension and Package

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  release:
    types: [ created ]

jobs:
  build:
    # Linux と Windows のマトリックス定義
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false # 1つのジョブが失敗しても他のジョブは継続する
      matrix:
        include:
          - name: Windows
            os: windows-latest
            php: '8.3'
            ts: nts
            sdkversion: '2.2.0'
            vsalias: vs16
            vcvarsopt: '-vcvars_ver=14.2'
        # os: [ubuntu-latest, windows-latest] # ビルドするOS
        # php: ['8.1', '8.2', '8.3'] # ビルド対象のPHPバージョン
        # Windows ビルドでは NTS (Non Thread Safe) が一般的。必要なら TS も追加
        # ts: [nts] # 必要なら [nts, ts]

    name: Build on ${{ matrix.os }} for PHP ${{ matrix.php }}

    steps:
    # 1. リポジトリのコードをチェックアウト
    - name: Checkout code
      uses: actions/checkout@v4

    # 2. 指定したPHPバージョンをセットアップ
    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: ${{ matrix.php }}
        extensions: none # この拡張自体をビルドするため、他の拡張は不要
        # tools: phpize, php-config # Linuxでは有用だがWindowsでは不要
        # ini-values: opcache.enable=0 # 必要に応じてINI設定を追加
        # coverage: none
        # env:
        #  PHP_SDK_VS_VERSION: 2019 # Windows で使用する VS のバージョンを指定する場合
      env:
        phpts: ${{ matrix.ts }} # スレッドセーフティをマトリックスにする場合
        COMPOSER_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    # 3. ビルドとパッケージングに必要な依存パッケージをインストール (OS別に分岐)
    - name: Install build and packaging dependencies (Ubuntu)
      if: ${{ startsWith(matrix.os, 'ubuntu-') }}
      run: |
        sudo apt-get update --allow-releaseinfo-change
        # build-essential: コンパイラ等, dpkg-dev: dpkg-debを含む, fakeroot: root権限なしでファイル所有者を偽装
        sudo apt-get install -y build-essential dpkg-dev fakeroot php${{ matrix.php }}-dev # php-devパッケージも明示的にインストール

    - name: Download and Setup PHP SDK & Source (Windows)
      if: ${{ startsWith(matrix.os, 'windows-') }}
      shell: pwsh
      run: |
        # Find the latest Visual Studio installation path with VSWhere
        $vsPath = & "${env:ProgramFiles(x86)}\Microsoft Visual Studio\Installer\vswhere.exe" -latest -property installationPath
        if ($vsPath) {
          $vcvarsallPath = Join-Path $vsPath "VC\Auxiliary\Build\vcvarsall.bat"
          echo "VS_VCVARSALL=$vcvarsallPath" | Out-File -FilePath $env:GITHUB_ENV -Encoding utf8 -Append
          Write-Host "Found vcvarsall at: $vcvarsallPath"
        } else {
          Write-Error "Visual Studio not found"
          exit 1
        }
        $phpFullVersion = php -r "echo PHP_VERSION;" # Get full version like 8.x.y
        if ($phpFullVersion) {
          echo "PHP_FULL_VERSION=$phpFullVersion" | Out-File -FilePath $env:GITHUB_ENV -Encoding utf8 -Append
          Write-Host "PHP version : $phpFullVersion"
        } else {
          Write-Error "PHP not found"
          exit 1
        }
        $sdkUrl = "https://github.com/microsoft/php-sdk-binary-tools/archive/refs/tags/php-sdk-${{ matrix.sdkversion }}.zip"
        $devPackUrl = "https://windows.php.net/downloads/releases/php-devel-pack-${phpFullVersion}-${{ matrix.ts }}-Win32-${{ matrix.vsalias }}-x64.zip"
        $currentDir = (Get-Location).Path

        Write-Host "SDK URL: $sdkUrl"
        Write-Host "Dev Pack Url: $devPackUrl"
        
        # Download and extract SDK
        echo "Downloading SDK..."
        Invoke-WebRequest -Uri $sdkUrl -OutFile php-sdk.zip
        Expand-Archive -Path php-sdk.zip -DestinationPath . -Force
        Remove-Item php-sdk.zip
        $sdkPath = Join-Path -Path $currentDir -ChildPath 'php-sdk-binary-tools-php-sdk-${{ matrix.sdkversion }}\msys2\usr\bin'
        echo "PHP_SDK_PATH=$sdkPath" | Out-File -FilePath $env:GITHUB_ENV -Encoding utf8 -Append
        Write-Host "PHP SDK PATH : $sdkPath"

        # Download and extract Dev Pack
        echo "Downloading DevPack..."
        Invoke-WebRequest -Uri $devPackUrl -OutFile php-dev-pack.zip
        Expand-Archive -Path php-dev-pack.zip -DestinationPath . -Force
        Remove-Item php-dev-pack.zip
        $devPackFolder = "php-${phpFullVersion}-devel-${{ matrix.vsalias }}-x64"
        $devPack = Join-Path -Path $currentDir -ChildPath $devPackFolder
        echo "PHP_DEV_PACK=$devPack" | Out-File -FilePath $env:GITHUB_ENV -Encoding utf8 -Append
        Write-Host "PHP DEV PACK : $devPack"
    
    # 4. 拡張機能のバージョンを取得 (php_rindow_operatorovl.hから取得)
    - name: Get Extension version from header
      id: ext_version
      shell: bash # Windows でも sed を使うために bash を指定
      run: |
        # sed を使用してバージョン番号を抽出
        VERSION=$(sed -n 's/^ *# *define PHP_RINDOW_OPERATOROVL_VERSION *"\([^"]*\)".*/\1/p' php_rindow_operatorovl.h)
        # 念のためバージョンが取得できたかチェック
        if [[ -z "$VERSION" ]]; then
          echo "Error: Could not extract version from php_rindow_operatorovl.h"
          cat php_rindow_operatorovl.h || true
          exit 1
        fi
        echo "version=${VERSION}" >> $GITHUB_OUTPUT
        echo "Extracted version: ${VERSION}"

    # 5. PHP拡張をビルド (OS別に分岐)
    - name: Build extension (Linux)
      if: ${{ startsWith(matrix.os, 'ubuntu-') }}
      run: |
        phpize${{ matrix.php }} # phpize もバージョン指定
        ./configure --with-php-config=$(which php-config${{ matrix.php }}) --enable-rindow_operatorovl
        make clean
        make

    - name: Build extension (Windows)
      if: ${{ startsWith(matrix.os, 'windows-') }}
      shell: cmd
      run: |
        REM Ensure PATH includes MSVC tools (should be set by msvc-dev-cmd action)
        REM PHP SDK PATH should be set by previous step using GITHUB_PATH or add-path
        call "%VS_VCVARSALL%" x64 ${{ matrix.vcvarsopt }}
        PATH %PATH%;%PHP_SDK_PATH%

        call "%PHP_DEV_PACK%\phpize"
  
        REM Configure the build (adjust paths and options if needed)
        REM Ensure config.w32 is used, enable the extension
        call configure --enable-rindow_operatorovl --with-prefix=C:\tools\php
  
        nmake clean
        nmake

    # 6. テストを実行 (OS別に分岐)
    - name: Run tests (Linux)
      if: ${{ startsWith(matrix.os, 'ubuntu-') }}
      run: make test
      env:
        NO_INTERACTION: 1
        REPORT_EXIT_STATUS: 1
        TEST_PHP_EXECUTABLE: /usr/bin/php${{ matrix.php }} # 念のため指定

    - name: Run tests (Windows)
      if: ${{ startsWith(matrix.os, 'windows-') }}
      shell: cmd
      run: |
        call "%VS_VCVARSALL%" x64 ${{ matrix.vcvarsopt }}
        PATH %PATH%;%PHP_SDK_PATH%
        nmake test
      env:
        NO_INTERACTION: 1
        REPORT_EXIT_STATUS: 1
        # TEST_PHP_EXECUTABLE は nmake 環境では自動で設定されることが多い

    # ---- Linux (.deb) パッケージングステップ ----
    - name: Determine DEB Artifact Info (Linux)
      if: ${{ startsWith(matrix.os, 'ubuntu-') }}
      id: deb_artifact_info
      run: |
        chmod +x packaging.sh
        run: ./packaging.sh ${{ matrix.php }}
        PACKAGE_NAME=$(grep '^Package:' pkgwork/DEBIAN/control | cut -d' ' -f2)
        VERSION="${{ steps.ext_version.outputs.version }}"
        ARCHITECTURE=$(dpkg --print-architecture)
        DEB_FILENAME="${PACKAGE_NAME}_${VERSION}_${ARCHITECTURE}.deb"
        if [[ ! -f "$DEB_FILENAME" ]]; then
          echo "Error: Expected DEB file '$DEB_FILENAME' not found!"
          ls -l *.deb || true
          exit 1
        fi
        echo "path=${DEB_FILENAME}" >> $GITHUB_OUTPUT
        echo "name=${DEB_FILENAME}" >> $GITHUB_OUTPUT
        echo "Built DEB artifact: ${DEB_FILENAME}"
      shell: bash

    - name: Upload DEB artifact (Linux)
      if: ${{ startsWith(matrix.os, 'ubuntu-') }}
      uses: actions/upload-artifact@v4
      with:
        name: ${{ steps.deb_artifact_info.outputs.name }}
        path: ${{ steps.deb_artifact_info.outputs.path }}
        retention-days: 7

    - name: Upload Release Asset (DEB) (Linux)
      if: ${{ startsWith(matrix.os, 'ubuntu-') && github.event_name == 'release' }}
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ github.event.release.upload_url }}
        asset_path: ${{ steps.deb_artifact_info.outputs.path }}
        asset_name: ${{ steps.deb_artifact_info.outputs.name }}
        asset_content_type: application/vnd.debian.binary-package

    # ---- Windows (.dll) 成果物ステップ ----
    - name: Determine DLL Artifact Info (Windows)
      if: ${{ startsWith(matrix.os, 'windows-') }}
      id: dll_artifact_info
      shell: pwsh
      run: |
        dir -Path . -Filter php_rindow_operatorovl.dll -Recurse -File
        $dllPath = (Get-ChildItem -Recurse -Filter php_rindow_operatorovl.dll -ErrorAction SilentlyContinue | Select-Object -First 1).FullName
        if (-not $dllPath) {
          echo "Error: Built DLL file (php_rindow_operatorovl.dll) not found!"
          Get-ChildItem -Recurse | Select-Object FullName -First 100
          exit 1
        }
        $zipName = "rindow_operatorovl-php${{ matrix.php }}-${{ steps.ext_version.outputs.version }}-${{ matrix.ts }}-x64.zip" # PHPバージョン等を付与
        Compress-Archive -Path $dllPath -DestinationPath $zipName -Force
        echo "DLL path found: $dllPath"
        echo "Artifact name: $zipName"
        echo "path=$dllPath" >> $env:GITHUB_OUTPUT
        echo "name=$dllName" >> $env:GITHUB_OUTPUT

    - name: Upload DLL artifact (Windows)
      if: ${{ startsWith(matrix.os, 'windows-') }}
      uses: actions/upload-artifact@v4
      with:
        name: ${{ steps.dll_artifact_info.outputs.name }}
        path: ${{ steps.dll_artifact_info.outputs.path }}
        retention-days: 7

    - name: Upload Release Asset (DLL) (Windows)
      if: ${{ startsWith(matrix.os, 'windows-') && github.event_name == 'release' }}
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ github.event.release.upload_url }}
        asset_path: ${{ steps.dll_artifact_info.outputs.path }}
        asset_name: ${{ steps.dll_artifact_info.outputs.name }}
        asset_content_type: application/octet-stream # DLLの標準的なMIMEタイプ
